global:
  scrape_interval: 5s
  
scrape_configs:
  - job_name: 'mybigwhale'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.17.0.1:8080'] #Servidor da minha aplicação
        labels:
         application: "mybigwhale"